clusters:
- name: minikube
  destinationServer: https://kubernetes.default.svc
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"

    sampleApp:
      enabled: true
      branch: HEAD

- name: gke
  destinationServer: https://172.18.0.4:6443
  apps:
    prometheus:
      enabled: true
      version: "9.7.4"
    sampleApp:
      enabled: true
      branch: HEAD
